language: go

go:
- 1.15.2

env:
  - CGO_CFLAGS_ALLOW="-Xpreprocessor"

addons:
  apt:
    packages:
      - libvips-dev
  homebrew:
    packages:
      - vips
      - pkg-config

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode12.2