language: go

go:
- 1.15.2

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - libvips-dev
  homebrew:
    packages:
      - vips

jobs:
  include:
    - os: linux
      dist: focal
    - os: osx
      osx_image: xcode12.2